model:
  model_name_or_path: "NbAiLab/nb-bert-base"
  tokenizer_name: "NbAiLab/nb-bert-base"
  cache_dir: None
  model_revision: main
  use_fast_tokenizer: None
  use_auth_token: False

data:
  dataset_name: ajders/ddisco
  lang: da
  overwrite_cache: False
  validation_split_percentage: 5
  max_seq_length: 256
  preprocessing_num_workers: 8
  mlm_probability: 15
  line_by_line: False
  pad_to_max_length: True
  max_train_samples: None
  max_eval_samples: False

training:
  output_dir: checkpoints
  overwrite_output_dir: True
  do_train: True
  do_eval: True
  do_predict: True
  evaluation_strategy: steps
  eval_steps: 5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 16
  eval_accumulation_steps: 16
  learning_rate: 2e-5
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-8
  max_grad_norm: 1.0
  num_train_epochs: 6.0
  lr_scheduler_type: linear
  warmup_ratio: 0.05
  log_level: info
  logging_strategy: steps
  logging_steps: 5
  save_strategy: steps
  save_steps: 15
  save_total_limit: 3
  seed: 703
  load_best_model_at_end: True
  push_to_hub: True
  hub_model_id: ajders/ddisco_classifier
  hub_strategy: every_save
  no_cuda: False